### ISSUE TITLE
ansible-lint > 6 breaks molecule

### ISSUE THREAD

**Issue by jsf9k** [cisagov/skeleton-ansible-role#101]
# 🐛 Summary #

Something about `ansible-lint >= 6` breaks `molecule`.  `molecule`'s `dependency` stage runs, but the roles are not picked up in `molecule`'s `lint` stage.

## To reproduce ##

See #100.

## Expected behavior ##

We should be able to upgrade to the latest `ansible-lint` without breaking `molecule`.

## Any helpful log output or screenshots ##

See [here](https://github.com/cisagov/skeleton-ansible-role/runs/5622267017?check_suite_focus=true#step:6:35), for example.

**Comment by dav3r** [comment]
@jsf9k @mcdonnnj - This issue can be closed now, right?  We moved from ansible-lint 5.4 to 6.17 in #147 (see https://github.com/cisagov/skeleton-ansible-role/pull/147/files#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9R134-R139).

**Comment by mcdonnnj** [comment]
@dav3r Ah I was looking at this last week and thinking the same. Yes I believe this can be closed out once it's linked to a PR (just for bookkeeping).

**Comment by jsf9k** [comment]
> @jsf9k @mcdonnnj - This issue can be closed now, right? We moved from ansible-lint 5.4 to 6.17 in #147 (see https://github.com/cisagov/skeleton-ansible-role/pull/147/files#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9R134-R139).

Yes, I think this issue should have been resolved by cisagov/skeleton-generic#136 or [the Lineage PR for this repo that contained those changes](https://github.com/cisagov/skeleton-ansible-role/pull/147).

**Comment by mcdonnnj** [comment]
@dav3r @jsf9k Actually after looking at this it is wholly separate from the `ansible-lint` version used with `pre-commit`. This is a carryover from when `molecule` had a `lint` stage and `ansible-lint` was directly installed. Please see #144 for what actually resolves this I believe (since the dependency was completely removed).

**Comment by dav3r** [comment]
Closing this issue since it was resolved by #144.
