### ISSUE TITLE
Provide install docs and/or publish to ansible galaxy

### ISSUE THREAD

**Issue by gionn** [cisagov/skeleton-ansible-role#167]
# 🐛 Summary #

README doesn't provide any guidance on how to use this role

## Expected behavior ##

At least the role published on ansible galaxy for easy install

Thanks!

**Comment by jsf9k** [comment]
The use of roles that are available via GitHub repositories [is documented in the `ansible-galaxy` documentation](https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#installing-multiple-roles-from-a-file), but I will add a blurb to the `README.md` file in this repository.  This addition will percolate down to _all_ of our Ansible role repositories via [cisagov/action-lineage](https://github.com/cisagov/action-lineage).

**Comment by jsf9k** [comment]
Thanks for the issue @gionn!  Please see PR #168.
