### ISSUE TITLE
Molecule builds currently broken

### ISSUE THREAD

**Issue by jsf9k** [cisagov/skeleton-ansible-role#69]
# 🐛 Summary #

[Version 5 of `ansible-lint` has been released](https://github.com/ansible-community/ansible-lint/releases/tag/v5.0.0), and it contains some breaking changes that have yet to shake out.

See:
* https://github.com/ansible-community/ansible-lint/discussions/1150
* https://github.com/ansible-community/ansible-lint/issues/1329
* https://github.com/ansible-community/ansible-lint/issues/1344

## To reproduce ##

1. Check out the code for any cisagov Ansible role that is based on [cisagov/skeleton-ansible-role](https://github.com/cisagov/skeleton-ansible-role) or [cisagov/skeleton-ansible-role-with-test-user](https://github.com/cisagov/skeleton-ansible-role-with-test-user).
2. Run `pip install --upgrade -r requirements-dev.txt`.
3. Run `molecule test` and watch it fail.

## Expected behavior ##

`molecule test` should complete successfully for any cisagov Ansible role that is based on [cisagov/skeleton-ansible-role](https://github.com/cisagov/skeleton-ansible-role) or [cisagov/skeleton-ansible-role-with-test-user](https://github.com/cisagov/skeleton-ansible-role-with-test-user).

## Any helpful log output or screenshots ##

For an example of this bug in an APB build, see [here](https://github.com/cisagov/ansible-role-nvme/actions/runs/568458801).

**Comment by dav3r** [comment]
@cisagov/team-ois - Is this issue still valid or can it now be closed out?

**Comment by jsf9k** [comment]
> @cisagov/team-ois - Is this issue still valid or can it now be closed out?

I have mentioned this issue in [the relevant PR](https://github.com/cisagov/skeleton-ansible-role/pull/85).
