### ISSUE TITLE
Remove Fedora 32 as a supported platform

### ISSUE THREAD

**Issue by mcdonnnj** [cisagov/skeleton-ansible-role#83]
# 💡 Summary #

The Fedora 32 platform should be removed.

## Motivation and context ##

With Fedora 32 [going EOL on 2021-05-25](https://fedorapeople.org/groups/schedule/f-32/f-32-all-tasks.html) we should stop supporting it as a platform once any images currently built on that version are upgraded to work with a later version of Fedora.

## Implementation notes ##

Currently this platform is in use in [cisagov/freeipa-server-packer](https://github.com/cisagov/freeipa-server-packer/blob/9b8f41c5157e7986f663bd2ab57da5fa2f156f52/src/packer.json#L33). That is the only image that appears to be built on Fedora 32, so as soon as that image is updated to use a later version of Fedora it should be fine to remove support.

## Acceptance criteria ##

- [x] [cisagov/freeipa-server-packer](https://github.com/cisagov/freeipa-server-packer) is no longer built on Fedora 32
- [x] Fedora 32 is removed from the supported platforms for our Ansible configurations.

**Comment by jsf9k** [comment]
@mcdonnnj - I believe this is now resolved.  Can you confirm and add a link to the relevant PR?

**Comment by dav3r** [comment]
I believe these are the relevant PRs:
* https://github.com/cisagov/skeleton-ansible-role/pull/95
* https://github.com/cisagov/freeipa-server-packer/pull/74
